# Generated by Django 4.1 on 2022-08-31 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="account",
            new_name="seller",
        ),
    ]
